[package]
name = "bobcat-source"
description = "Lynx XML, web and native source-bundle parsing and Bobcat source adaptation"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
bobcat-core = { workspace = true }
bobcat-resources = { workspace = true }
bytecheck = { workspace = true }
rkyv = { workspace = true }
serde_json = { workspace = true }
cssparser = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }

[dev-dependencies]
divan = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = { workspace = true }

[lints]
workspace = true

[[bench]]
name = "decode"
harness = false

[[example]]
name = "dump"

[[example]]
name = "convert"
