import { createHash } from 'node:crypto';
import { readFile, readdir, rename, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { basename, dirname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

import type { RsbuildPlugin } from '@rsbuild/core';

const require = createRequire(import.meta.url);
const sourceRoot = fileURLToPath(new URL('../src/', import.meta.url));
const sha256 = (value: string | Uint8Array) => createHash('sha256').update(value).digest('hex');
const version = (name: string): string => require(`${name}/package.json`).version;

interface CompilerSources {
  customSections: Record<string, { content: string | Record<string, unknown>; encoding?: string }>;
}

// The shared build hook emits native source sections. This hook names the
// fixture pages and records what each selected environment built.
export function pluginSourceBundles(mode: string, engineVersion: string): RsbuildPlugin {
  return {
    name: 'bobcat:source-fixture-bundles',
    setup(api) {
      api.onAfterBuild(async () => {
        const output = fileURLToPath(new URL('../dist/', import.meta.url));
        const entries: string[] = [];
        for (const file of (await readdir(output)).sort()) {
          if (!file.endsWith('.provenance.json')) continue;
          const name = file.replace('.provenance.json', '');
          const metadata: { bundles: Record<string, string>; publicPath?: string | null } =
            JSON.parse(await readFile(join(output, file), 'utf8'));
          // The page is the one bundle at the top of the output directory; lazy
          // bundles live in a subdirectory whose name Rsbuild owns.
          const page = Object.keys(metadata.bundles).find(path => !path.includes('/'));
          if (!page) throw new Error(`No page bundle for ${name}`);
          const chunks = Object.keys(metadata.bundles).filter(path => path.includes('/')).sort();
          entries.push(`        ${JSON.stringify(name)} => Fixture {
            page: include_bytes!(${JSON.stringify(`${name}/${page}`)}),
            chunks: &[${chunks.map(path => `(${JSON.stringify(path)}, include_bytes!(${JSON.stringify(`${name}/${path}`)}))`).join(',')}],
            public_path: ${metadata.publicPath ? `Some(${JSON.stringify(metadata.publicPath)})` : 'None'},
        },`);
        }
        await writeFile(join(output, 'index.rs'), `// Generated by the fixture build. Do not commit.
#[rustfmt::skip]
#[allow(clippy::too_many_lines, reason = "generated fixture table")]
pub fn fixture(name: &str) -> Fixture {
    match name {
${entries.join('\n')}
        _ => panic!("unknown fixture: {name}"),
    }
}
`);
      });
      api.onAfterEnvironmentCompile(async ({ environment, stats }) => {
        if (!stats || stats.hasErrors()) return;
        const [fixture] = Object.keys(environment.entry);
        if (!fixture) throw new Error('A fixture environment needs an entry');
        const output = environment.distPath;
        const native = environment.name.startsWith('lynx-');
        let nativePageSha256: string | undefined;
        let publicPath: string | null = null;
        let scripts: Record<string, string> | undefined;
        if (native) {
          const options: CompilerSources = JSON.parse(await readFile(join(output, `.lynx/${fixture}/tasm.json`), 'utf8'));
          const mainThread = options.customSections[`${fixture}__main-thread`]?.content;
          if (typeof mainThread !== 'string') throw new Error('Compiled page source section was not found');
          const publicPathMatch = mainThread.match(/__webpack_require__\.p\s*=\s*("(?:[^"\\]|\\.)*")/);
          if (mode === 'development' && !publicPathMatch) throw new Error('Compiled page public path was not found');
          publicPath = publicPathMatch?.[1] ? JSON.parse(publicPathMatch[1]) : null;
          const page = join(output, `${fixture}.${environment.name}.bundle`);
          nativePageSha256 = sha256(await readFile(page));
          await rename(page, join(output, `${fixture}.lynx.bundle`));
          scripts = Object.fromEntries(Object.entries(options.customSections)
            .filter((section): section is [string, { content: string }] => typeof section[1].content === 'string')
            .map(([name, { content }]) => [name, sha256(content)]));
        }
        const bundles: Record<string, string> = {};
        for (const file of (await readdir(output, { recursive: true })).sort()) {
          if (file.endsWith('.bundle') && !file.startsWith('.')) {
            bundles[file] = sha256(await readFile(join(output, file)));
          }
        }
        const sources = Array.from(stats.compilation.fileDependencies)
          .filter(file => file.startsWith(sourceRoot))
          .map(file => relative(sourceRoot, file).split(sep).join('/')).sort();
        await writeFile(join(dirname(output), `${basename(output)}.provenance.json`), JSON.stringify({
          sources, target: native ? 'lynx' : 'web', mode, engineVersion,
          description: native ? 'Native source sections emitted directly by the compiler.' : 'Unmodified web compiler output.',
          publicPath, nativePageSha256, scripts, bundles,
          encoder: `@lynx-js/tasm@${version('@lynx-js/tasm')}`,
          react: version('@lynx-js/react'), rsbuild: version('@rsbuild/core'),
          reactPlugin: version('@lynx-js/react-rsbuild-plugin'),
        }, null, 2) + '\n');
      });
    },
  };
}
